Added first part of Lab2
studentfedorov/java pull request #2
Opened 2017-09-23 20:09 UTC by studentfedorov

Tests for HashTable

2017-09-25 06:04 UTC, jzuken requested changes

2017-09-25 06:04 UTC, jzuken commented on Lab02_1/src/main/java/ru/spbau/fedorov/algo/HashTable.java
> +package ru.spbau.fedorov.algo;
э, нет, не надо сюда копировать файлы из первой домашки. этот пуллреквест должен добавлять только тесты, их имеет смысл добавить прямо в ту папку, где лежал код. откройте новый пуллреквест, пожалуйста

2017-09-25 06:04 UTC, jzuken commented on Lab02_1/src/test/java/ru/spbau/fedorov/test/HashTableTest.java
> +public class HashTableTest {
хочется тест на разрешение коллизий ещё

2017-09-25 06:11 UTC, studentfedorov commented on Lab02_1/src/main/java/ru/spbau/fedorov/algo/HashTable.java
> +package ru.spbau.fedorov.algo;
У меня вроде как еще изменилась структура папок. Просто закоммитить сразу в master все, кроме тестов?

2017-09-25 22:26 UTC, studentfedorov commented
Пришлось помучится, чтобы сделать в pull request только тесты (правда есть еще минорные фиксы к проектным файлам)

2017-09-26 11:23 UTC, jzuken commented on Lab02_1/src/main/java/ru/spbau/fedorov/algo/HashTable.java
> +package ru.spbau.fedorov.algo;
надо было везде поменять, значит

2017-09-27 19:17 UTC, merged

2017-10-05 13:22 UTC, jzuken commented
я не понял, а почему это пуллреквест замерджен? я задачу не принимал

2017-10-05 13:23 UTC, jzuken commented
откатите, пожалуйста, мердж в мастер

2017-10-05 14:32 UTC, studentfedorov commented
Эмм, нет, спасибо
Новый pull request находится здесь и ссылка на него есть в hwproj:
https://github.com/studentfedorov/java/pull/4

Этот был примержен, чтобы поменять структуру папок/добавить maven файлы для того, чтобы в pull request остались только файлы тестов

2017-10-05 18:13 UTC, jzuken commented
так, я вроде разобрался, что вы тут наделали. это жесть, не делайте так больше