Added Lab04
studentfedorov/java pull request #7
Opened 2017-10-10 11:23 UTC by studentfedorov

2017-10-21 06:46 UTC, jzuken requested changes

2017-10-21 06:46 UTC, jzuken commented on Lab04/src/main/java/ru/spbau/fedorov/algo/ZipFile.java
> +     * @throws IOException
исключения тоже надо документировать

2017-10-21 06:46 UTC, jzuken commented on Lab04/src/main/java/ru/spbau/fedorov/algo/ZipFile.java
> +        return (magicBytes == 0x504b0304) || (magicBytes == 0x504b0506) || (magicBytes == 0x504b0708);
сурово

2017-10-21 06:46 UTC, jzuken commented on Lab04/src/main/java/ru/spbau/fedorov/algo/ZipFile.java
> +    private static void UnzipMatchingRegex(@NotNull String zipName, @NotNull String regex, @NotNull String path) throws IOException{
этот явно зря с заглавной буквы именуется

2017-10-22 18:00 UTC, studentfedorov commented on Lab04/src/main/java/ru/spbau/fedorov/algo/ZipFile.java
> +        return (magicBytes == 0x504b0304) || (magicBytes == 0x504b0506) || (magicBytes == 0x504b0708);
Но вроде это лучше, чем попробовать открыть как zip и ловить исключения. Кроме того, никто не виноват, что там для zip файлов выделено аж три последовательности байтов.

2017-11-06 08:21 UTC, merged